### ISSUE TITLE
The Docker image can no longer be built

### ISSUE THREAD

**Issue by C0D3D3V** [aramperes/code-jam-3#1]
I know this is a dead project. But I just wanted to test it because I am interested in the technologies used...
It turned out that the Docker image can no longer be built.
Maybe you want to have a look at it.

```
❯ docker-compose up -d
Sending build context to Docker daemon  65.94kB
Step 1/5 : FROM python:3.6.5-stretch
 ---> 9a58cce9b09f
Step 2/5 : ADD . .
 ---> Using cache
 ---> 9e1e55a16ba1
Step 3/5 : RUN pip install pipenv
 ---> Using cache
 ---> 096aa0fb3176
Step 4/5 : RUN pipenv sync
 ---> Running in 856e493150d2
Creating a virtualenv for this project...
Pipfile: /Pipfile
Using /usr/local/bin/python3.6m (3.6.5) to create virtualenv...
⠋ Creating virtual environment...created virtual environment CPython3.6.5.final.0-64 in 1207ms
  creator CPython3Posix(dest=/root/.local/share/virtualenvs/-x-v5uFv0, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
    added seed packages: pip==21.3.1, setuptools==59.6.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment!
Virtualenv location: /root/.local/share/virtualenvs/-x-v5uFv0
Installing dependencies from Pipfile.lock (2257d9)...
An error occurred while installing markupsafe==1.0 --hash=sha256:a6be69091dac236ea9c6bc7d012beab42010fa914c459791d627dad4910eb665! Will try again.
Installing initially failed dependencies...
[pipenv.exceptions.InstallError]: Collecting markupsafe==1.0
[pipenv.exceptions.InstallError]:   Using cached MarkupSafe-1.0.tar.gz (14 kB)
[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): started
[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): finished with status 'error'
[pipenv.exceptions.InstallError]: ERROR: Command errored out with exit status 1:
[pipenv.exceptions.InstallError]:    command: /root/.local/share/virtualenvs/-x-v5uFv0/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-82uzuy4l/markupsafe_4ceefb4a7a47499483b3be8cba6a8071/setup.py'"'"'; __file__='"'"'/tmp/pip-install-82uzuy4l/markupsafe_4ceefb4a7a47499483b3be8cba6a8071/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-q0kse6n6
[pipenv.exceptions.InstallError]:        cwd: /tmp/pip-install-82uzuy4l/markupsafe_4ceefb4a7a47499483b3be8cba6a8071/
[pipenv.exceptions.InstallError]:   Complete output (5 lines):
[pipenv.exceptions.InstallError]:   Traceback (most recent call last):
[pipenv.exceptions.InstallError]:     File "<string>", line 1, in <module>
[pipenv.exceptions.InstallError]:     File "/tmp/pip-install-82uzuy4l/markupsafe_4ceefb4a7a47499483b3be8cba6a8071/setup.py", line 6, in <module>
[pipenv.exceptions.InstallError]:       from setuptools import setup, Extension, Feature
[pipenv.exceptions.InstallError]:   ImportError: cannot import name 'Feature'
[pipenv.exceptions.InstallError]:   ----------------------------------------
[pipenv.exceptions.InstallError]: WARNING: Discarding https://files.pythonhosted.org/packages/4d/de/32d741db316d8fdb7680822dd37001ef7a448255de9699ab4bfcbdf4172b/MarkupSafe-1.0.tar.gz#sha256=a6be69091dac236ea9c6bc7d012beab42010fa914c459791d627dad4910eb665 (from https://pypi.org/simple/markupsafe/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
[pipenv.exceptions.InstallError]: ERROR: Could not find a version that satisfies the requirement markupsafe==1.0 (from versions: 0.9, 0.9.1, 0.9.2, 0.9.3, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.20, 0.21, 0.22, 0.23, 1.0, 1.1.0, 1.1.1, 2.0.0a1, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1)
[pipenv.exceptions.InstallError]: ERROR: No matching distribution found for markupsafe==1.0
ERROR: Couldn't install package: markupsafe
 Package installation failed...
1 error occurred:
	* Status: The command '/bin/sh -c pipenv sync' returned a non-zero code: 1, Code: 1
```

**Comment by aramperes** [comment]
Looks like `markupsafe` needs to be updated to `1.1.1`: https://github.com/pallets/markupsafe/issues/116

**Comment by C0D3D3V** [comment]
Thank you for taking the time for looking into this. With the change of Pipfile.lock the container can actually be built. 

The game itself stops with the message "`Loading terrain (100%)...`". (In the console `world:ready null`) But that is not so important to me for now, I just wanted to see how you did it. Thanks a lot.

**Comment by aramperes** [comment]
Yeah unfortunately my team ran out of time for that hackathon so we did not complete, but hopefully you find something useful in here!

I will update the Pipfile later today (or if you want to submit a PR)

**Comment by aramperes** [comment]
Hey @C0D3D3V, I managed to make this project run again. Basically, it froze at `Loading terrain (100%)` because of a missing step. If you clone and follow these steps it should work:

```sh
# Compile the flexx app
cd client
pipenv install
pipenv run python compile.py
cd ..

# Build the pixi client
cd client/js
npm install
npm run webpack
cd ..

# Copy the spritesheet
cp -r client/js/img services/client-host/project/static

# Build and run
docker-compose up -d --build
```

Naturally this setup is bit messy, but I wasn't very experienced with monorepos or Docker back then. When everything works, you get a generated terran you can navigate with mouse pan/zoom:

![image](https://user-images.githubusercontent.com/6775216/152898109-b4d82e46-c6b6-4909-85bf-7eadcbd74f11.png)

**Comment by C0D3D3V** [comment]
Remains unchanged for me unfortunately, but is not so important, I have already looked at your code and understood how everything was implemented. Really great work.
